# Default values for Syncthing.

image:
  repository: syncthing/syncthing
  pullPolicy: IfNotPresent
  tag: "1.18"

strategy:
  type: Recreate

service:
  main:
    ports:
      main:
        port: 8384
  listeners:
    ports:
      tcp:
        enabled: true
        port: 22000
        protocol: TCP
      udp:
        enabled: true
        port: 22000
        protocol: UDP
  discovery:
    ports:
      discovery:
        enabled: true
        port: 21027
        protocol: UDP

persistence:
  config:
    enabled: true
    type: emptyDir

    mountPath: "/var/syncthing/"
