# Default values for Jackett.

image:
  repository: ghcr.io/k8s-at-home/jackett
  pullPolicy: IfNotPresent
  tag: v0.18.616

strategy:
  type: Recreate


service:
  main:
    enabled: true
    ports:
      main:
        port: 9117

probes:
  liveness:
    path: "/UI/Login"

  readiness:
    path: "/UI/Login"

  startup:
    path: "/UI/Login"

env: {}
  # TZ: UTC
  # PUID: 1001
  # PGID: 1001


persistence:
  config:
    enabled: true
    mountPath: "/config"
    type: emptyDir
