##
# This file contains Values.yaml content that gets added to the output of questions.yaml
# It's ONLY meant for content that the user is NOT expected to change.
# Example: Everything under "image" is not included in questions.yaml but is included here.
##

image:
  repository: weblate/weblate
  pullPolicy: IfNotPresent
  tag: 4.8-1

#All values here are set as the docker defaults.
envTpl:
  # Permissions Settings
  USER_ID: "{{ .Values.env.PUID }}"
  GROUP_ID: "{{ .Values.env.PGID }}"

# Enabled postgres
postgresql:
  # postgresql.postgresqlUsername -- PostgreSQL user should be a superuser to
  # be able to install pg_trgm extension. Alternatively you can install it
  # manually prior starting Weblate.
  postgresqlUsername: "postgres"
  postgresqlPassword: "weblate"
  postgresqlDatabase: "weblate"
  service:
    port: 5432
  enabled: true
  # postgresql.postgresqlHost -- External postgres database endpoint, to be
  # used if `postgresql.enabled == false`
  # @default -- `None`
  postgresqlHost:

redis:
  password: "weblate"
  db: 1
  enabled: true
  # redis.redisHost -- External redis database endpoint, to be
  # used if `redis.enabled == false`
  # @default -- `None`
  redisHost:
  cluster:
    enabled: false

##
# Most other defaults are set in questions.yaml
# For other options please refer to the wiki, default_values.yaml or the common library chart
##
